### ISSUE TITLE
missing file reconstruct_tv.m?

### ISSUE THREAD

**Issue by yyy-git** [Computational-Periscopy/Ordinary-Camera#1]
when I try to run script fig4_column_e or fig_S1_S2, MATLAB(R2017a) complains 
Undefined function or variable 'reconstruct_tv'.

Error in fig_S1_S2 
    final_im1(:,:,:,count) = reconstruct_tv(sr*simA,sg*simA,sb*simA, test_image1,  3.25*tv_reg_param, NumBlocks_sim);

**Comment by Computational-Periscopy** [comment]
Thanks for bringing this to our attention - now fixed.
