### ISSUE TITLE
Matrix dimensions must agree.

### ISSUE THREAD

**Issue by 201528014227051** [Computational-Periscopy/Ordinary-Camera#2]
thanks for the released codes and data;
this error is occurred in simulate_block.m when i try to run the fig_S14.m.

tmp = arrayfun(@calc,repmat(vs(1,:,:) + vs2,[walln_points,1,1]) + repmat(permute(vs(2,:,:),[2,1,3]),[1,walln_points,1]));

I changed the code to 
tmp = arrayfun(@calc,repmat(vs(1,:,:) + repmat(vs2,[1,1,36]),[walln_points,1,1]) + repmat(permute(vs(2,:,:),[2,1,3]),[1,walln_points,1]));

to make the code run successfully.

But is this right?

Looking forward your replay.

**Comment by Computational-Periscopy** [comment]
I have not run the changed version but from inspection it looks ok. The error may be caused by the way different versions of MATLAB operate. Thank you for sharing this fix.
